# Generated by Django 5.1.1 on 2024-09-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('hire_date', models.DateField()),
                ('job_end_date', models.DateField(blank=True, null=True)),
                ('is_currently_working', models.BooleanField(default=True)),
            ],
        ),
    ]
